name: Deploy Infrastructure

description: Deploy infrastructure to the chosen environment.

inputs:
  environment:
    required: true
    description: 'The environment to deploy to'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Deploy Azure
      if: ${{ inputs.environment == 'azure' }}
      uses: ./.github/workflows/azure/main.yml

    - name: Deploy GCP
      if: ${{ inputs.environment == 'gcp' }}
      uses: ./.github/workflows/gcp/main.yml

    - name: Deploy AWS
      if: ${{ inputs.environment == 'aws' }}
      uses: ./.github/workflows/aws/main.yml
