name: 2-Apply-Azure

on:
  release:
    types:
      - created
  workflow_dispatch:
#   push:
#     branches:
#       - main  

jobs:
  apply-deploy:
    name: 'Apply iNfra Azure'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate to Az CLI using OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./src/azure

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./src/azure

      - name: Terraform apply
        run: terraform apply --auto-approve
        working-directory: ./src/azure        

      - name: Obrtendo IP publico
        id: get_public_ip
        run: echo "::set-output name=public_ip::$(terraform output public_ip_address)"
        working-directory: ./src/azure

      - name: Obrtendo IP publico e criando uma variavel
        run: |
          echo "Public IP Address: ${{ steps.get_public_ip.outputs.public_ip }}"
        working-directory: ./src/azure          

      - name: Instalando Nginx
        run: |
          PUBLIC_IP=$(terraform output public_ip_address)
          ssh -o StrictHostKeyChecking=no adminuser@$PUBLIC_IP 'sudo apt-get update && sudo apt-get install -y nginx'
        working-directory: ./src/azure          
